WEB_SRC_FILES = \
webrtcmoudle/analog_agc.c \
webrtcmoudle/complex_bit_reverse.c \
webrtcmoudle/complex_fft.c \
webrtcmoudle/copy_set_operations.c \
webrtcmoudle/cross_correlation.c \
webrtcmoudle/digital_agc.c \
webrtcmoudle/division_operations.c \
webrtcmoudle/dot_product_with_scale.c \
webrtcmoudle/downsample_false.c \
webrtcmoudle/energy.c \
webrtcmoudle/fft4g.c \
webrtcmoudle/get_scaling_square.c \
webrtcmoudle/min_max_operations.c \
webrtcmoudle/noise_suppression.c \
webrtcmoudle/noise_suppression_x.c \
webrtcmoudle/ns_core.c \
webrtcmoudle/nsx_core.c \
webrtcmoudle/nsx_core_c.c \
webrtcmoudle/nsx_core_neon_offsets.c \
webrtcmoudle/real_fft.c \
webrtcmoudle/resample.c \
webrtcmoudle/resample_48khz.c \
webrtcmoudle/resample_by_2.c \
webrtcmoudle/resample_by_2_internal.c \
webrtcmoudle/resample_fractional.c \
webrtcmoudle/ring_buffer.c \
webrtcmoudle/spl_inl.c \
webrtcmoudle/spl_sqrt.c \
webrtcmoudle/spl_sqrt_floor.c \
webrtcmoudle/splitting_filter.c \
webrtcmoudle/vector_scaling_operations.c